/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
/* tslint:disable */
export var styles = ['body,html{height:100%;font-family:Arial,Helvetica,sans-serif}a.active{background-color:gray}'];
//# sourceMappingURL=app.component.css.ngstyle.js.map